services:
  - type: web
    name: wallet-tool-backend
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free  # Puoi rimuovere o cambiare se usi un piano a pagamento
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    buildFilter:
      paths:
        - backend/**
