services:
  - type: web
    name: wallet-tool-backend
    env: python
    region: frankfurt
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn app:app
    wsgi:
      application_port: 5000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11  # Cambia a 3.11
    buildFilter:
      paths:
        - backend/**
