services:
  - type: web
    name: backend
    env: docker
    plan: free
    repo: https://github.com/collezionegrenga/wallet-tool
    region: frankfurt
    dockerfilePath: ./Dockerfile
    buildFilter:
      paths:
        - backend/**
